### ISSUE TITLE
#1 matheduude | Bugg/Fehler report

### ISSUE THREAD

**Issue by matheduude** [ZionHost/dashboard#1]
Hallo ich habe einen fehler gefunden der bei mir so vorkommt.
1. Ich gehe auf https://zion.host/Login/Beta
2. Ich Melde mich an.
3. Ich Klicke auf "weiter".
Nun sollte man wahrscheinlich Weitergeleitet werden, ist bei mir aber nicht so!
Ich bleibe auf der Seite und nichts passiert.

Mats

**Comment by mkg20001** [comment]
Warte mal was genau meinst du jetzt? Auf welcher seite wirst du nicht weitergeleitet

**Comment by matheduude** [comment]
https://zion.host/Login/Beta dort steht wenn man sich Angemeldet hat ganz groß Weiter
bei mir geht diese Weiterleitung aber nicht. :ice_cream:

**Comment by matheduude** [comment]
![unbenanntwas](https://cloud.githubusercontent.com/assets/18212295/14205998/1f5fcf76-f810-11e5-83e8-2b2211237e6f.PNG)

**Comment by matheduude** [comment]
Dort leitet er mich nicht weiter.

**Comment by mkg20001** [comment]
hast du schon drauf geklickt?
oder kannst du nicht drauf klicken

**Comment by matheduude** [comment]
Ich kann rauf klicken aber es passiert nichts.

**Comment by mkg20001** [comment]
lade die seite mal neu, sollte jetzt funktionieren

**Comment by matheduude** [comment]
Ja super Funktioniert! :-)

**Comment by mkg20001** [comment]
Ok, dann ist das mal erledigt
